version: "3.8"

services:
  db:
    image: postgres:15
    container_name: corecity_db
    environment:
      POSTGRES_DB: corecity_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: demo123
    ports:
      - "5432:5432"
    volumes:
      - ./database/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./database/seed.sql:/docker-entrypoint-initdb.d/2-seed.sql
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: corecity_adminer
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  pgdata:
